import { resolveTokenData } from '../data/dataAggregator';
import { scoreRisk, analyzeMarket, createTradePlan } from '../ai';
import { AlphaReport, QuickCheckResult } from '../types';
import { getCachedReport, setCachedReport, getCachedQuickCheck, setCachedQuickCheck } from './cache';

function formatNumber(n: number | null | undefined): string {
  if (n === null || n === undefined) return 'Unknown';
  if (n >= 1e9) return (n / 1e9).toFixed(2) + 'B';
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(2) + 'K';
  if (n < 1 && n > 0) return n.toFixed(6);
  return n.toFixed(2);
}

function generateMarkdown(report: Omit<AlphaReport, 'markdown'>): string {
  const { token, risk, market, trade } = report;
  
  return `
# 🔎 Prism Intelligence: ${token.symbol}
**${token.name}** | Price: $${formatNumber(token.price)} | 24h: ${token.priceChange24h > 0 ? '🟢 +' : '🔴 '}${token.priceChange24h.toFixed(2)}%

---

## ⚠️ Risk Shield: ${risk.level} (Score: ${risk.score}/100)
${risk.summary}

**Key Risk Factors Detected:**
${risk.flags.length > 0 ? risk.flags.map(f => `- ${f}`).join('\n') : '- None detected'}

---

## 📊 Market Structure: ${market.trend}
${market.summary}

- **Trend Strength:** ${market.strength}/100
- **Volume Pattern:** ${market.volumeAnomaly.replace('_', ' ')}
- **Key Support:** ${market.support ? '$' + formatNumber(market.support) : 'Unknown'}
- **Key Resistance:** ${market.resistance ? '$' + formatNumber(market.resistance) : 'Unknown'}

---

## ${trade.verdictEmoji} AI Trade Plan: ${trade.verdict}
*Confidence: ${trade.confidenceScore}/100*

${trade.reasoning}

### Actionable Levels
- **Entry Zone:** $${formatNumber(trade.entryZone?.low)} - $${formatNumber(trade.entryZone?.high)}
- **Stop Loss:** $${formatNumber(trade.stopLoss)}
- **Take Profits:** 
  - TP1: $${formatNumber(trade.takeProfits?.tp1)}
  - TP2: $${formatNumber(trade.takeProfits?.tp2)}
  - TP3: $${formatNumber(trade.takeProfits?.tp3)}
- **Risk/Reward:** ${trade.riskRewardRatio}

> *Generated by Prism in ${report.generatedInMs}ms using ${token.source.toUpperCase()} data.*
`;
}

export async function generateFullReport(identifier: string, chain?: string): Promise<AlphaReport> {
  const startTime = Date.now();
  
  const cached = getCachedReport(identifier);
  if (cached) {
    const freshData = await resolveTokenData(identifier, chain); // still want fresh price potentially? no, full report is cached
    return cached;
  }

  // 1. Fetch Data
  const tokenData = await resolveTokenData(identifier, chain);
  
  // 2. AI Pipeline
  const risk = await scoreRisk(tokenData);
  const market = await analyzeMarket(tokenData, risk);
  const trade = await createTradePlan(tokenData, risk, market);
  
  // 3. Assemble
  const reportBase = {
    requestId: Math.random().toString(36).substring(7),
    timestamp: new Date().toISOString(),
    token: tokenData,
    risk,
    market,
    trade,
    generatedInMs: Date.now() - startTime
  };

  const finalReport: AlphaReport = {
    ...reportBase,
    markdown: generateMarkdown(reportBase).trim()
  };

  setCachedReport(identifier, finalReport);
  
  return finalReport;
}

export async function buildQuickCheck(identifier: string, chain?: string): Promise<QuickCheckResult> {
  const cached = getCachedQuickCheck(identifier);
  if (cached) return cached;

  const tokenData = await resolveTokenData(identifier, chain);
  
  // Quick heuristic for risk level without calling AI
  let riskLevel = 'MEDIUM';
  if (!tokenData.marketCap) riskLevel = 'HIGH (Unknown MC)';
  if (tokenData.liquidityUSD !== null && tokenData.liquidityUSD < 100000) riskLevel = 'EXTREME (Low Liq)';
  if (Math.abs(tokenData.priceChange24h) > 30) riskLevel = 'HIGH (Volatile)';

  const result: QuickCheckResult = {
    symbol: tokenData.symbol,
    price: tokenData.price,
    change24h: tokenData.priceChange24h,
    volume24h: tokenData.volume24h,
    riskLevel,
    verdict: 'Unlock Full Report for Trade Plan',
    note: 'This is a free snapshot. Request full analysis for AI strategy.'
  };

  setCachedQuickCheck(identifier, result);
  
  return result;
}
